version: "3.7"
services:
  #web:
  #  container_name: nginx-python
  #  image: nginx:latest
  #  depends_on:
  #    - app
  #  ports:
  #    - 8082:80
  #  volumes:
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #  networks:
  #    - default
  db-main:
    image: postgres:latest
    container_name: db_aggreco
    restart: always
    expose:
      - 5435
    ports:
      - 5435:5435
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
  #app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: app_document
  #  ports:
  #    - 9999:8000
  #  command: ["/app/docker/wait-for-it.sh", "db-main:6000", "-t 30", "--", "/app/docker/app.sh"]
  #  env_file:
  #    - .env-deploy
  #  depends_on:
  #    - db-main
  #    - pgadmin
  pgadmin:
    container_name: pgadmin_document
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db-main
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  minio:
    container_name: files_s3
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    env_file:
      - .env
    command: server --console-address ":9001" /data