"""empty message

Revision ID: 0116c18d9c70
Revises: 5b9d83a87f7c
Create Date: 2025-01-20 16:49:50.085589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0116c18d9c70'
down_revision: Union[str, None] = '5b9d83a87f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.add_column('object', sa.Column('id_region', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'object', 'region', ['id_region'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'object', type_='foreignkey')
    op.drop_column('object', 'id_region')
    op.drop_table('region')
    # ### end Alembic commands ###
