"""empty message

Revision ID: 07fee63f4ad7
Revises: ea716d3b2ac4
Create Date: 2025-05-21 21:22:55.460692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fee63f4ad7'
down_revision: Union[str, None] = 'ea716d3b2ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('last_datetime_edit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'last_datetime_edit')
    # ### end Alembic commands ###
