"""empty message

Revision ID: 08b84a53a1ae
Revises: 6145902346e2
Create Date: 2024-10-22 20:16:01.426298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b84a53a1ae'
down_revision: Union[str, None] = '6145902346e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_claim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('claim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_state_claim', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('main_document', sa.String(), nullable=True),
    sa.Column('edit_document', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_state_claim'], ['state_claim.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim')
    op.drop_table('state_claim')
    # ### end Alembic commands ###
