"""empty message

Revision ID: 1956171c70d2
Revises: 901d9789e823
Create Date: 2024-11-01 14:57:48.048004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1956171c70d2'
down_revision: Union[str, None] = '901d9789e823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_document', sa.Column('datetime', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_document', 'datetime')
    # ### end Alembic commands ###
