"""empty message

Revision ID: 255bbb8347e5
Revises: f4f89395a4d9
Create Date: 2024-06-11 14:14:54.757184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255bbb8347e5'
down_revision: Union[str, None] = 'f4f89395a4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(), nullable=True))
    op.add_column('user', sa.Column('patronymic', sa.String(), nullable=True))
    op.add_column('user', sa.Column('id_profession', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_foreign_key(None, 'user', 'profession', ['id_profession'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'id_profession')
    op.drop_column('user', 'patronymic')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_table('profession')
    # ### end Alembic commands ###
