"""empty message

Revision ID: 2bb8d118ca26
Revises: 7ac2e584d399
Create Date: 2024-10-15 10:33:18.467728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb8d118ca26'
down_revision: Union[str, None] = '7ac2e584d399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_accident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('accident', sa.Column('id_state_accident', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accident', 'state_accident', ['id_state_accident'], ['id'])
    op.drop_column('accident', 'additional_material')
    op.add_column('user', sa.Column('painting', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'painting')
    op.add_column('accident', sa.Column('additional_material', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accident', type_='foreignkey')
    op.drop_column('accident', 'id_state_accident')
    op.drop_table('state_accident')
    # ### end Alembic commands ###
