"""empty message

Revision ID: 399ebadf1a52
Revises: 5dfec0d8655c
Create Date: 2026-01-11 16:03:57.322071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '399ebadf1a52'
down_revision: Union[str, None] = '5dfec0d8655c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summatize', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('summatize', sa.Column('metadata_equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summatize', 'metadata_equipment')
    op.drop_column('summatize', 'create_at')
    # ### end Alembic commands ###
