"""empty message

Revision ID: 3daf9bced3cd
Revises: 164fbfe4e4d0
Create Date: 2024-06-19 17:29:22.644012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3daf9bced3cd'
down_revision: Union[str, None] = '164fbfe4e4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'is_deleted')
    # ### end Alembic commands ###
