"""empty message

Revision ID: 42f7a442cfa9
Revises: adffd22107d6
Create Date: 2025-04-08 18:07:18.563118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f7a442cfa9'
down_revision: Union[str, None] = 'adffd22107d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('responsible', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'responsible')
    # ### end Alembic commands ###
