"""empty message

Revision ID: 44044ed411f5
Revises: 0b17013c833d
Create Date: 2024-07-15 14:12:20.028048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44044ed411f5'
down_revision: Union[str, None] = '0b17013c833d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_brake',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type_brake',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_type'], ['class_brake.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_table('type_brake_organizational')
    op.drop_table('type_brake_mechanical')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_brake_mechanical',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='type_brake_mechanical_pkey'),
    sa.UniqueConstraint('code', name='type_brake_mechanical_code_key')
    )
    op.create_table('type_brake_organizational',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='type_brake_organizational_pkey'),
    sa.UniqueConstraint('code', name='type_brake_organizational_code_key')
    )
    op.drop_table('type_brake')
    op.drop_table('class_brake')
    # ### end Alembic commands ###
