"""empty message

Revision ID: 5b9d83a87f7c
Revises: 8e0f898488d5
Create Date: 2025-01-13 15:04:52.412187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9d83a87f7c'
down_revision: Union[str, None] = '8e0f898488d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('is_delite', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'is_delite')
    # ### end Alembic commands ###
