"""empty message

Revision ID: 5dfec0d8655c
Revises: 76eb4a90313b
Create Date: 2026-01-09 15:04:47.865108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dfec0d8655c'
down_revision: Union[str, None] = '76eb4a90313b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_messages_error',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('id_object', sa.Integer(), nullable=True),
    sa.Column('id_equipment', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('class_log_text', sa.String(), nullable=False),
    sa.Column('class_log_int', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('entity_equipment', sa.String(), nullable=True),
    sa.Column('number_equipment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_equipment'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['id_object'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('summatize',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('id_object', sa.Integer(), nullable=True),
    sa.Column('id_equipment', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_equipment'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['id_object'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('object', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'settings')
    op.drop_table('summatize')
    op.drop_table('log_messages_error')
    # ### end Alembic commands ###
