"""empty message

Revision ID: 6145902346e2
Revises: 2bb8d118ca26
Create Date: 2024-10-19 16:56:36.338871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6145902346e2'
down_revision: Union[str, None] = '2bb8d118ca26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('additional_material', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accident', 'additional_material')
    # ### end Alembic commands ###
