"""empty message

Revision ID: 621591393348
Revises: cb7a6ee754a9
Create Date: 2024-07-15 13:03:14.642299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621591393348'
down_revision: Union[str, None] = 'cb7a6ee754a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_equipment', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'type_equipment', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type_equipment', type_='unique')
    op.drop_column('type_equipment', 'code')
    # ### end Alembic commands ###
