"""empty message

Revision ID: 705f6827a830
Revises: e57665c37dea
Create Date: 2024-08-27 17:08:14.442726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705f6827a830'
down_revision: Union[str, None] = 'e57665c37dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accident_additional_material_key', 'accident', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('accident_additional_material_key', 'accident', ['additional_material'])
    # ### end Alembic commands ###
