"""empty message

Revision ID: 76eb4a90313b
Revises: e5c1a9addc49
Create Date: 2025-10-12 21:01:34.008202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76eb4a90313b'
down_revision: Union[str, None] = 'e5c1a9addc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technical_proposals', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_proposals', 'name')
    # ### end Alembic commands ###
