"""empty message

Revision ID: 7bd9dac0e047
Revises: f9e89eb7dc05
Create Date: 2024-01-10 13:52:28.423235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd9dac0e047'
down_revision: Union[str, None] = 'f9e89eb7dc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('id_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'type_user', ['id_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'id_type')
    op.drop_table('type_user')
    # ### end Alembic commands ###
