"""empty message

Revision ID: 8e0f898488d5
Revises: 1956171c70d2
Create Date: 2025-01-10 18:33:26.963330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0f898488d5'
down_revision: Union[str, None] = '1956171c70d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_document', sa.Column('name', sa.String(), nullable=True))
    op.add_column('file_document', sa.Column('size', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_document', 'size')
    op.drop_column('file_document', 'name')
    # ### end Alembic commands ###
