"""empty message

Revision ID: 901c59955a35
Revises: 7bd9dac0e047
Create Date: 2024-01-11 11:39:27.052595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901c59955a35'
down_revision: Union[str, None] = '7bd9dac0e047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('url_document', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'url_document')
    # ### end Alembic commands ###
