"""empty message

Revision ID: 901d9789e823
Revises: 0bcebdf39135
Create Date: 2024-11-01 14:53:27.359654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901d9789e823'
down_revision: Union[str, None] = '0bcebdf39135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_document')
    # ### end Alembic commands ###
