"""empty message

Revision ID: 9084be7825b4
Revises: ad9426fbcf10
Create Date: 2025-01-21 12:58:45.290291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9084be7825b4'
down_revision: Union[str, None] = 'ad9426fbcf10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signs_accident_to_accident',
    sa.Column('id_accident', sa.Integer(), nullable=False),
    sa.Column('id_signs_accident', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_accident'], ['accident.id'], ),
    sa.ForeignKeyConstraint(['id_signs_accident'], ['signs_accident.id'], ),
    sa.PrimaryKeyConstraint('id_accident', 'id_signs_accident')
    )
    op.drop_constraint('accident_id_signs_accident_fkey', 'accident', type_='foreignkey')
    op.drop_column('accident', 'id_signs_accident')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('id_signs_accident', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('accident_id_signs_accident_fkey', 'accident', 'signs_accident', ['id_signs_accident'], ['id'])
    op.drop_table('signs_accident_to_accident')
    # ### end Alembic commands ###
