"""empty message

Revision ID: 9969e83ada01
Revises: obj_equip_fk_to_uuid
Create Date: 2026-03-17 12:02:03.012238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9969e83ada01'
down_revision: Union[str, None] = 'obj_equip_fk_to_uuid'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_error_accident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accident', sa.Column('id_error_code_accident', sa.Integer(), nullable=True))
    op.add_column('accident', sa.Column('reason_for_shutdown', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'accident', 'code_error_accident', ['id_error_code_accident'], ['id'])
    op.alter_column('equipment_to_accident', 'uuid_equipment',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('user_to_document', sa.Column('user_uuid', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_to_document', 'user_uuid')
    op.alter_column('equipment_to_accident', 'uuid_equipment',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'accident', type_='foreignkey')
    op.drop_column('accident', 'reason_for_shutdown')
    op.drop_column('accident', 'id_error_code_accident')
    op.drop_table('code_error_accident')
    # ### end Alembic commands ###
