"""empty message

Revision ID: ab2e037a3f16
Revises: 3daf9bced3cd
Create Date: 2024-06-21 14:13:30.321757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2e037a3f16'
down_revision: Union[str, None] = '3daf9bced3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('id_object', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'object', ['id_object'], ['id'])
    op.drop_constraint('object_id_equipment_fkey', 'object', type_='foreignkey')
    op.drop_column('object', 'id_equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('id_equipment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('object_id_equipment_fkey', 'object', 'equipment', ['id_equipment'], ['id'])
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'id_object')
    # ### end Alembic commands ###
