"""empty message

Revision ID: ad9426fbcf10
Revises: 0116c18d9c70
Create Date: 2025-01-21 12:13:31.852127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9426fbcf10'
down_revision: Union[str, None] = '0116c18d9c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signs_accident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('accident', sa.Column('id_signs_accident', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accident', 'signs_accident', ['id_signs_accident'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accident', type_='foreignkey')
    op.drop_column('accident', 'id_signs_accident')
    op.drop_table('signs_accident')
    # ### end Alembic commands ###
