"""empty message

Revision ID: ba7c88a7739a
Revises: 399ebadf1a52
Create Date: 2026-01-11 17:31:41.708101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba7c88a7739a'
down_revision: Union[str, None] = '399ebadf1a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summatize', sa.Column('datetime_start', sa.DateTime(), nullable=False))
    op.add_column('summatize', sa.Column('datetime_end', sa.DateTime(), nullable=True))
    op.drop_column('summatize', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summatize', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('summatize', 'datetime_end')
    op.drop_column('summatize', 'datetime_start')
    # ### end Alembic commands ###
