"""empty message

Revision ID: cb7a6ee754a9
Revises: ab2e037a3f16
Create Date: 2024-07-15 12:24:05.995371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb7a6ee754a9'
down_revision: Union[str, None] = 'ab2e037a3f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_error',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('equipment', sa.Column('code', sa.String(), nullable=True))
    op.add_column('equipment', sa.Column('characteristics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'equipment', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='unique')
    op.drop_column('equipment', 'characteristics')
    op.drop_column('equipment', 'code')
    op.drop_table('code_error')
    # ### end Alembic commands ###
