"""empty message

Revision ID: e57665c37dea
Revises: e638d3e37baf
Create Date: 2024-08-27 17:07:07.103360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57665c37dea'
down_revision: Union[str, None] = 'e638d3e37baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accident', ['additional_material'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accident', type_='unique')
    # ### end Alembic commands ###
