"""empty message

Revision ID: e5c1a9addc49
Revises: b7ca7e8e7495
Create Date: 2025-10-12 17:15:44.975536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c1a9addc49'
down_revision: Union[str, None] = 'b7ca7e8e7495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('id_state_claim', sa.Integer(), nullable=True),
    sa.Column('id_object', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_expert', sa.Integer(), nullable=True),
    sa.Column('offer', sa.Text(), nullable=True),
    sa.Column('additional_material', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('last_datetime_edit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_expert'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_object'], ['object.id'], ),
    sa.ForeignKeyConstraint(['id_state_claim'], ['state_claim.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_proposals')
    # ### end Alembic commands ###
