"""empty message

Revision ID: ea716d3b2ac4
Revises: 42f7a442cfa9
Create Date: 2025-05-07 12:15:54.587346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea716d3b2ac4'
down_revision: Union[str, None] = '42f7a442cfa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('is_delite', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accident', 'is_delite')
    # ### end Alembic commands ###
