"""empty message

Revision ID: ed89bf06376c
Revises: 9084be7825b4
Create Date: 2025-01-21 16:03:24.407800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed89bf06376c'
down_revision: Union[str, None] = '9084be7825b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('time_zone', sa.String(), server_default='+03:00', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accident', 'time_zone')
    # ### end Alembic commands ###
